"""Initial migration

Revision ID: 01d8a3767d64
Revises: 93e0d5b86d03
Create Date: 2023-05-08 13:40:28.838932

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '01d8a3767d64'
down_revision = '93e0d5b86d03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
