"""Initial migration

Revision ID: 06705b1d6081
Revises: 01d8a3767d64
Create Date: 2023-05-08 13:50:40.129862

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '06705b1d6081'
down_revision = '01d8a3767d64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
