"""Initial migration

Revision ID: 6a353c3ace52
Revises: 06705b1d6081
Create Date: 2023-05-08 13:51:53.471215

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6a353c3ace52'
down_revision = '06705b1d6081'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
