"""Initial migration

Revision ID: d1c20a320315
Revises: 6a353c3ace52
Create Date: 2023-05-08 13:52:49.980452

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd1c20a320315'
down_revision = '6a353c3ace52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
