[tool.black]
line-length = 88
targer-version = ['py311']

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
ensure_newline_before_comments = true
line_length = 88

[tool.autoflake]
check_diff = true

[tool.pyright]
include = ["app"]